data(cheeses)
p_cva=profileCVA(profileObject=cheeses)
resCVA_Multi=profileCVA(profileObject=cheeses,option="MultiMAM")
resCVA_MAM=profileCVA(profileObject=cheeses,option="MAM")
#profileCVA(profileObject=cheeses, test="Hotelling-Lawley",option="TwoWayANOVA", itemsToPlot=c("ProductEllipses","ProductSegments","ProductLabels","AttributeLabels"), representation="Biplot", nbAxes="Auto", outputs=NULL,confInt=0.9,ellipsesType="barycentric",productColors=FALSE,fileName=NULL,ellipsesCalculation="Chi",onlySignificantAttributesInMultivariateAnalysis=TRUE,alphaForSelectionOfSignificantAttributes=0.05)
