TS_SetProfileMultivariateAnalysisParameters=function(profileObject, onlySignificantAttributesInMultivariateAnalysis,alphaForSelectionOfSignificantAttributes)
{
	profileObject[["OnlySignificantAttributesInMultivariateAnalysis"]]=onlySignificantAttributesInMultivariateAnalysis
	profileObject[["AlphaForSelectionOfSignificantAttributes"]]=alphaForSelectionOfSignificantAttributes
	
	return(profileObject)
}
